name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Format
        run: |
          pip install black
          black --check .

      - name: Lint
        run: |
          pip install flake8
          flake8 --ignore E203,W503, --max-line-length 115 .

      - name: Type check
        run: |
          pip install mypy
          mypy . --ignore-missing-imports --no-strict-optional --no-site-packages --cache-dir=/dev/null

      - name: Run tests
        run: |
          pip install pytest
          pytest --color=yes -rf --durations=40
